### ISSUE TITLE
Can't get the Game to start

### ISSUE THREAD

**Issue by rpsteiger** [obilodeau/ceopardy#10]
Hello obilodeau,
We are hosting a hacker jeopardy event with customers soon and you ceopardy would be perfect for it.
I tried to get it to run yesterday and somewhat failed at that.  
Currently I can get it to start but the player screen keeps finding no host. See screenshots below:
![Screenshot 2022-08-19 at 11 08 49](https://user-images.githubusercontent.com/1891583/185585956-8e2c8c31-24dd-4118-9a5b-acdfd5f9476f.png)
![Screenshot 2022-08-19 at 11 09 02](https://user-images.githubusercontent.com/1891583/185585966-d7ba67ad-0109-4354-b26e-71e224e38e37.png)

Also, I made some modifications to JS dependency mapping. I replaced bower with npm, since bower does not contain up to date version of the socket.io js client. I tried to push my branch into your repo but I keep getting a `Permission to obilodeau/ceopardy.git denied to rpsteiger.` Is that supposed to be this way? It's my first time trying to push to a public repository.

Anyway to wrap things up. I think the issue that I am having with ceopardy is that I use the wrong socket.io version. Can you tell me which version of the pip and bower packages you are using?

**Comment by obilodeau** [comment]
Redirect bug fixed with eada1aa
