### ISSUE TITLE
Would like to get in touch

### ISSUE THREAD

**Issue by rpsteiger** [obilodeau/ceopardy#11]
Hey obilodeau,
I modernized ceopardy in my fork and added a feature that allows the host to view the correct answer (or question) on his screen. I was going to write you an email, but there is no email in your profile.

**Comment by obilodeau** [comment]
That's great! You want to contribute it back? You can find my email by doing `git log` on the repo.

**Comment by obilodeau** [comment]
Still willing and interested!

**Comment by obilodeau** [comment]
I understand that you might have moved on. Closing. Re-open if necessary.
